/**
 * Copyright 2018 The AMP HTML Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS-IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

module.exports = tags = {

  selfClosingTags: new Set([
      'area',
      'base',
      'basefont',
      'bgsound',
      'br',
      'col',
      'embed',
      'frame',
      'hr',
      'img',
      'input',
      'keygen',
      'link',
      'meta',
      'param',
      'source',
      'track',
      'wbr',
    ]),

  allTags: new Set([
      '!DOCTYPE',
      'a',
      'abbr',
      'acronym',
      'abbr',
      'address',
      'applet',
      'area',
      'article',
      'aside',
      'audio',
      'b',
      'base',
      'basefont',
      'bdi',
      'bdo',
      'big',
      'blockquote',
      'body',
      'br',
      'button',
      'canvas',
      'caption',
      'center',
      'cite',
      'code',
      'col',
      'colgroup',
      'data',
      'datalist',
      'dd',
      'del',
      'details',
      'dfn',
      'dialog',
      'dir',
      'div',
      'dl',
      'dt',
      'em',
      'embed',
      'fieldset',
      'figcaption',
      'figure',
      'font',
      'footer',
      'form',
      'frame',
      'frameset',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'head',
      'header',
      'hr',
      'html',
      'i',
      'iframe',
      'img',
      'input',
      'ins',
      'kbd',
      'label',
      'input',
      'legend',
      'li',
      'link',
      'main',
      'map',
      'mark',
      'meta',
      'meter',
      'nav',
      'noframes',
      'noscript',
      'object',
      'ol',
      'optgroup',
      'option',
      'output',
      'p',
      'param',
      'picture',
      'pre',
      'progress',
      'q',
      'rp',
      'rt',
      'ruby',
      's',
      'samp',
      'script',
      'section',
      'select',
      'small',
      'source',
      'span',
      'strike',
      's',
      'strong',
      'style',
      'sub',
      'summary',
      'sup',
      'svg',
      'table',
      'tbody',
      'td',
      'template',
      'textarea',
      'tfoot',
      'th',
      'thead',
      'time',
      'title',
      'tr',
      'track',
      'tt',
      'u',
      'ul',
      'var',
      'video',
      'wbr',
    ]),

  ampTags: new Set([
      'amp-pixel',
      'amp-ad-exit',
      'amp-ad',
      'amp-embed',
      'amp-analytics',
      'amp-auto-ads',
      'amp-call-tracking',
      'amp-experiment',
      'amp-share-tracking',
      'amp-sticky-ad',
      'amp-access-laterpay',
      'amp-access',
      'amp-byside-content',
      'amp-consent',
      'amp-date-picker',
      'amp-form',
      'amp-geo',
      'amp-gist',
      'amp-google-document-embed',
      'amp-install-serviceworker',
      'amp-next-page',
      'amp-selector',
      'amp-subscriptions-google',
      'amp-subscriptions',
      'amp-user-notification',
      'amp-web-push',
      'amp-layout',
      'amp-accordion',
      'amp-app-banner',
      'amp-carousel',
      'amp-fx-collection',
      'amp-fx-flying-carpet',
      'amp-iframe',
      'amp-image-lightbox',
      'amp-image-slider',
      'amp-lightbox-gallery',
      'amp-lightbox',
      'amp-orientation-observer',
      'amp-position-observer',
      'amp-sidebar',
      'amp-3d-gltf',
      'amp-3q-player',
      'amp-anim',
      'amp-apester-media',
      'amp-audio',
      'amp-bodymovin-animation',
      'amp-brid-player',
      'amp-brightcove',
      'amp-dailymotion',
      'amp-embedly-card',
      'amp-google-vrview-image',
      'amp-hulu',
      'amp-ima-video',
      'amp-imgur',
      'amp-izlesene',
      'amp-jwplayer',
      'amp-kaltura-player',
      'amp-mowplayer',
      'amp-nexxtv-player',
      'amp-o2-player',
      'amp-ooyala-player',
      'amp-playbuzz',
      'amp-reach-player',
      'amp-soundcloud',
      'amp-springboard-player',
      'amp-video-iframe',
      'amp-video',
      'amp-vimeo',
      'amp-viqeo-player',
      'amp-wistia-player',
      'amp-yotpo',
      'amp-youtube',
      'amp-animation',
      'amp-date-countdown',
      'amp-fit-text',
      'amp-font',
      'amp-mathml',
      'amp-pan-zoom',
      'amp-story',
      'amp-timeago',
      'amp-viz-vega',
      'amp-addthis',
      'amp-beopinion',
      'amp-facebook-comments',
      'amp-facebook-like',
      'amp-facebook-page',
      'amp-facebook',
      'amp-gfycat',
      'amp-instagram',
      'amp-pintrest',
      'amp-reddit',
      'amp-riddle-quiz',
      'amp-social-share',
      'amp-twitter',
      'amp-vine',
      'amp-vk'
    ]),

  /**
   * All dynamic amp-* element tags that could potentially add DOM elements to
   *    the page after first render via deferred JS execution.
   */
  exceptionTags: new Set([
    'amp-bind',
    'amp-list',
    'amp-live-list',
    'amp-mustache',
    'template' // Implementation of amp-mustache
    // 'amp-img',
  ]),

  disallowedStyles: new Set([
    '@keyframe',
    'transition'
  ]),

  selectorParts: [
      '+',
      '>',
      '.',
      '#',

  ]

};


